version: '3.7'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/domain.cert.pem:/etc/ssl/certs/domain.cert.pem
      - ./ssl/private.key.pem:/etc/ssl/private/private.key.pem

  cert-uploader:
    depends_on:
      - nginx-proxy
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: cert-uploader
    expose:
      - "8080"
    restart: always

